---
services:
  estro:
    image: ghcr.io/spaghetti-coder/estro:latest
    # build: .  # <- Uncomment for local builds
    container_name: estro
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      # - ~/.ssh:/home/node/.ssh:ro   # <- To allow remote commands
      - ./config.yaml:/app/config.yaml:ro
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/config"]
      interval: 30s
      timeout: 5s
      retries: 3
